# -*- coding: utf-8 -*-
import glob
import os
import sys
import tempfile
import subprocess

import puddlestuff.resource
import puddlestuff.findfunc as findfunc
import puddlestuff.loadshortcuts as loadshortcuts
from puddlestuff.puddleobjects import PuddleConfig

usage = '''Usage: python update_translation.py [-h] [-q] language

Options:
    language: Locale of the language to be created eg. en_ZA, rus, fr_BE.
    -q Quiet mode (only error messages will be shown).
    -h Show this message.'''


def parse_dialogs():
    from puddlestuff.mainwin import (tagpanel, artwork, dirview,
                                     filterwin, storedtags, logdialog)
    import puddlestuff.masstag.dialogs as masstag
    import puddlestuff.mainwin.tagsources as tagsources
    import puddlestuff.mainwin.action_dialogs as action_dialogs

    def tr(s):
        s = s.replace('"', r'\"')
        return 'translate("Dialogs", "%s")' % s

    dialog_strings = []
    controls = [z.control for z in [tagpanel, artwork, dirview, filterwin,
                                    tagsources, storedtags, logdialog, masstag]]

    controls.extend(action_dialogs.controls)

    return [tr(c[0]) for c in controls]


def parse_functions():
    func_strings = []

    def tr(s):
        return 'translate("Functions", "%s")' % s.replace('"', r'\"')

    for f in findfunc.functions:
        try:
            x = findfunc.Function(f)
            if len(x.info) > 1:
                func_strings.append(tr(x.info[1]))
            func_strings.append(tr(x.funcname))
            for controls in x._getControls(None):
                del (controls[1])
                func_strings.extend(list(map(tr, controls)))
        except AttributeError:
            pass

    return func_strings


def parse_shortcuts():

    def tr(s):
        s = s.replace('"', r'\"')
        return 'translate("Menus", "%s")' % s

    f = tempfile.NamedTemporaryFile('rb+')
    fn = f.name

    loadshortcuts.check_file(fn, 'data:./shortcuts')
    cparser = PuddleConfig(fn)

    action_strings = []
    setting = cparser.data
    for section in cparser.sections():
        if section.startswith('shortcut'):
            values = dict([(str(k), v) for k, v in setting[section].items()])
            action_strings.append(tr(values['name']))
            if 'tooltip' in values:
                action_strings.append(tr(values['tooltip']))

    f.close()
    menus = tempfile.NamedTemporaryFile('rb+')
    fn = menus.name
    loadshortcuts.check_file(fn, 'data:./menus')
    cparser = PuddleConfig(fn)

    action_strings.extend(list(map(tr, cparser.data['menu'])))
    menus.close()

    return action_strings


def write_translations():
    f = open('puddlestuff/translations.py', 'r+')
    out = []
    for i, l in enumerate(f.readlines()):
        out.append(l)
        if 'translate("Menus", "Sort &By")' in l:
            break

    f.seek(len(''.join(out)))
    f.write('\n# Below here is generated by `update_translation.py`')
    f.write('\n    ' + '\n    '.join(parse_shortcuts()))
    f.write('\n\n    # Functions\n    ' + '\n    '.join(parse_functions()))
    f.write('\n\n    # Dialogs\n    ' + '\n    '.join(parse_dialogs()))
    f.write('\n')
    f.truncate()
    f.close()


def get_translation_files(new_lang):
    translation_path = os.path.join('puddlestuff', 'translations')
    translation_files = glob.glob(os.path.join(translation_path, '*.ts'))

    new_filename = None
    if new_lang:
        new_filename = os.path.join(translation_path, f'puddletag_{new_lang}.ts')
        if new_filename not in translation_files:
            translation_files.append(new_filename)

    return sorted(translation_files), new_filename


verbose = True

try:
    lang = sys.argv[1]
    if lang.strip() == '-q':
        verbose = False
        lang = sys.argv[2]
except IndexError:
    print('Error: No language specified\n')
    print(usage)
    sys.exit(1)

if lang in ('--help', '-h'):
    print(usage)
    sys.exit(0)

if verbose:
    print('Updating `translations.py` from menu-/shortcut-/function-/dialog-sourcecode...\n')

write_translations()

if verbose:
    print('Updating translation keys in `*.ts` files from application sourcecode...')
try:
    translation_files, ts_file = get_translation_files(lang)

    def argument_generator():
        """Return all arguments to call pylupdate."""
        yield 'pylupdate6'
        yield '--no-obsolete'
        if verbose:
            yield '--verbose'
        for file in translation_files:
            yield '--ts'
            yield file
        yield 'puddlestuff'
    subprocess.run(argument_generator(), check=True)
except OSError:
    print('Error: pylupdate6 is not installed.')
    sys.exit(2)

if verbose:
    print(f'\nOpen {ts_file} in Qt Linguist in order to edit the translation.')
