
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xc6\xe3\xf3\xc6\x95\x89\xb3p\x9cV\xde\x8b\xfb\x99\x87\xdf'

_lr_action_items = {'STRING':([4,7,0,6,3,10,13,12,9,2,5,1,11,],[-2,1,1,1,-3,1,1,1,1,1,1,-4,-8,]),')':([9,11,13,8,10,3,1,7,4,],[-7,-8,-6,11,-1,-3,-4,-5,-2,]),'-':([5,12,0,6,13,3,1,10,9,7,4,2,11,],[2,2,2,2,2,-3,-4,2,2,-5,-2,2,-8,]),',':([9,4,8,13,3,1,7,11,10,],[-7,-2,12,-6,-3,-4,-5,-8,-1,]),'NUMBER':([7,13,5,9,12,4,2,3,1,10,0,6,11,],[-5,3,3,3,3,-2,3,-3,-4,3,3,3,-8,]),'STARTFUNC':([12,5,13,9,10,7,2,1,3,4,6,11,0,],[5,5,5,5,5,-5,5,-4,-3,-2,5,-8,5,]),'$end':([3,7,11,1,6,10,4,],[-3,-5,-8,-4,0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'arglist':([5,],[8,]),'expression':([12,2,6,13,9,10,7,5,0,],[13,7,10,10,10,10,10,9,6,]),'func':([13,0,6,9,12,2,5,10,7,],[4,4,4,4,4,4,4,4,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('expression',2,'p_expression','/home/keith/Documents/python/freetag/myparser.py',57),
  ('expression',1,'p_expression','/home/keith/Documents/python/freetag/myparser.py',58),
  ('expression',1,'p_expression','/home/keith/Documents/python/freetag/myparser.py',59),
  ('expression',1,'p_expression','/home/keith/Documents/python/freetag/myparser.py',60),
  ('expression',2,'p_expression_uminus','/home/keith/Documents/python/freetag/myparser.py',67),
  ('arglist',3,'p_arglist','/home/keith/Documents/python/freetag/myparser.py',73),
  ('arglist',1,'p_arglist','/home/keith/Documents/python/freetag/myparser.py',74),
  ('func',3,'p_expression_func','/home/keith/Documents/python/freetag/myparser.py',87),
]
