#!/usr/bin/env python
#puddletag.py

#Copyright (C) 2008-2009 concentricpuddle

#This file is part of puddletag, a semi-good music tag editor.

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import sys, os
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import pyqtRemoveInputHook
from puddlestuff.maintest import MainWin
pyqtRemoveInputHook()
__version__ = "0.8.3"
import logging

try:
  if sys.argv[1] == '--debug':
    logging.basicConfig(stream=sys.stderr,
                        level=logging.DEBUG,
                        )
    del(sys.argv[1])
except IndexError:
  pass

if len(sys.argv) > 1:
    filename = sys.argv[1]
else:
    filename = None

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setOrganizationName("Puddle Inc.")
    app.setApplicationName("puddletag")
    win = MainWin()
    win.setVisible(True)
    QApplication.processEvents()
    if filename and os.path.exists(filename):
        win.openDir(filename)
    app.exec_()